import type { Parameter } from './presets';

export const parameterRegistry: Record<Parameter, { label: string; kind: 'range' | 'toggle' | 'select' | 'stops' | 'origin-grid'; min?: number; max?: number; step?: number; options?: string[]; format?: (value: number) => string }> = {
  rollDirection: { label: 'Roll direction', kind: 'select', options: ['up', 'down'] },
  digitStagger: { label: 'Digit stagger', kind: 'range', min: 0, max: 80, step: 5, format: v => `${v}ms` },
  rollDistance: { label: 'Roll distance', kind: 'range', min: 24, max: 60, step: 1, format: v => `${v}px` },
  changedDigitsOnly: { label: 'Changed digits only', kind: 'toggle' },
  swapDirection: { label: 'Direction', kind: 'select', options: ['left', 'right', 'up', 'down'] },
  swapDistance: { label: 'Swap distance', kind: 'range', min: 4, max: 48, step: 1, format: v => `${v}px` },
  overlap: { label: 'Overlap', kind: 'range', min: 0, max: 1, step: .05, format: v => `${Math.round(v * 100)}%` },
  exitOpacity: { label: 'Exit opacity', kind: 'range', min: 0, max: .5, step: .05, format: v => `${Math.round(v * 100)}%` },
  sweepDirection: { label: 'Sweep direction', kind: 'select', options: ['right', 'left'] },
  sweepWidth: { label: 'Sweep width', kind: 'range', min: 10, max: 60, step: 5, format: v => `${v}%` },
  sweepIntensity: { label: 'Intensity', kind: 'range', min: .1, max: 1, step: .05, format: v => `${Math.round(v * 100)}%` },
  repeatMode: { label: 'Repeat mode', kind: 'select', options: ['once', 'loop'] },
  fanSpread: { label: 'Fan spread', kind: 'range', min: 20, max: 60, step: 1, format: v => `${v}px` },
  fanHeight: { label: 'Fan height', kind: 'range', min: 80, max: 180, step: 1, format: v => `${v}%` },
  arcDepth: { label: 'Arc depth', kind: 'range', min: 0, max: 20, step: 1, format: v => `${v}px` },
  sideRotation: { label: 'Side rotation', kind: 'range', min: 0, max: 18, step: 1, format: v => `${v}°` },
  inactiveScale: { label: 'Inactive scale', kind: 'range', min: .85, max: .98, step: .01, format: v => `${Math.round(v * 100)}%` },
  activeLift: { label: 'Active lift', kind: 'range', min: 0, max: 24, step: 1, format: v => `${v}px` },
  swipeSensitivity: { label: 'Swipe sensitivity', kind: 'range', min: .5, max: 1.5, step: .1, format: v => `${v.toFixed(1)}×` },
  dismissDirection: { label: 'Dismiss direction', kind: 'select', options: ['horizontal', 'left', 'right', 'free'] },
  threshold: { label: 'Threshold', kind: 'range', min: .15, max: .6, step: .05, format: v => `${Math.round(v * 100)}%` },
  rotationIntensity: { label: 'Rotation intensity', kind: 'range', min: 0, max: 24, step: 1, format: v => `${v}°` },
  exitDistance: { label: 'Exit distance', kind: 'range', min: 160, max: 400, step: 10, format: v => `${v}px` },
  velocitySensitivity: { label: 'Velocity sensitivity', kind: 'range', min: .5, max: 2, step: .1, format: v => `${v.toFixed(1)}×` },
  returnSpring: { label: 'Return spring', kind: 'range', min: .7, max: 1.4, step: .1, format: v => `${v.toFixed(1)}×` },
  flipAxis: { label: 'Flip axis', kind: 'select', options: ['y', 'x'] },
  perspective: { label: 'Perspective', kind: 'range', min: 400, max: 1200, step: 50, format: v => `${v}px` },
  rotationDirection: { label: 'Rotation direction', kind: 'select', options: ['clockwise', 'counterclockwise'] },
  midpointScale: { label: 'Midpoint scale', kind: 'range', min: .94, max: 1, step: .01, format: v => `${Math.round(v * 100)}%` },
  enterDirection: { label: 'Direction', kind: 'select', options: ['bottom', 'top', 'left', 'right'] },
  startOpacity: { label: 'Start opacity', kind: 'range', min: 0, max: 1, step: .1, format: v => `${Math.round(v * 100)}%` },
  startScale: { label: 'Start scale', kind: 'range', min: .9, max: 1, step: .01, format: v => `${Math.round(v * 100)}%` },
  delay: { label: 'Delay', kind: 'range', min: 0, max: 400, step: 20, format: v => `${v}ms` },
  triggerMode: { label: 'Trigger mode', kind: 'select', options: ['once', 'repeat'] },
  depth: { label: 'Press depth', kind: 'range', min: 1, max: 8, step: 1, format: v => `${v}px` },
  direction: { label: 'Direction', kind: 'select', options: ['forward', 'backward'] },
  cardScale: { label: 'Side card scale', kind: 'range', min: .90, max: .96, step: .01, format: v => `${Math.round(v * 100)}%` },
  peek: { label: 'Visible peek', kind: 'range', min: 8, max: 32, step: 1, format: v => `${v}px` },
  snapStrength: { label: 'Snap strength', kind: 'range', min: .7, max: 1.4, step: .1, format: v => `${v.toFixed(1)}×` },
  origin: { label: 'Origin', kind: 'origin-grid', options: ['top-left', 'top', 'top-right', 'left', 'center', 'right', 'bottom-left', 'bottom', 'bottom-right'] },
  duration: { label: 'Duration', kind: 'range', min: 80, max: 800, step: 10, format: v => `${v}ms` },
  distance: { label: 'Distance', kind: 'range', min: 0, max: 48, step: 1, format: v => `${v}px` },
  distanceX: { label: 'Move X', kind: 'range', min: -48, max: 48, step: 1, format: v => `${v}px` },
  scale: { label: 'Scale from', kind: 'range', min: .9, max: 1, step: .01, format: v => `${Math.round(v * 100)}%` },
  opacity: { label: 'Fade', kind: 'toggle' },
  bezierX1: { label: 'X1', kind: 'range', min: 0, max: 1, step: .01, format: v => v.toFixed(2) },
  bezierY1: { label: 'Y1', kind: 'range', min: -2, max: 3, step: .01, format: v => v.toFixed(2) },
  bezierX2: { label: 'X2', kind: 'range', min: 0, max: 1, step: .01, format: v => v.toFixed(2) },
  bezierY2: { label: 'Y2', kind: 'range', min: -2, max: 3, step: .01, format: v => v.toFixed(2) },
  easing: { label: 'Easing', kind: 'select', options: ['hold', 'linear', 'ease-in', 'ease-out', 'ease-in-and-out', 'ease-in-back', 'ease-out-back', 'ease-in-and-out-back', 'custom-bezier', 'smooth', 'snappy', 'spring'] },
  bounce: { label: 'Bounce', kind: 'range', min: 0, max: 30, step: 1, format: v => `${v}%` },
  hold: { label: 'Hold', kind: 'range', min: 0, max: 240, step: 10, format: v => `${v}ms` },
  repeatDelay: { label: 'Repeat pause', kind: 'range', min: 0, max: 1800, step: 100, format: v => `${v}ms` },
  stagger: { label: 'Stagger', kind: 'range', min: 30, max: 160, step: 10, format: v => `${v}ms` },
  intensity: { label: 'Intensity', kind: 'stops', options: ['subtle', 'normal', 'expressive'] },
};
