import { afterEach, expect, it, vi } from 'vitest';
import { createPreviewTimeline } from './previewTimeline';
afterEach(() => { vi.useRealTimers(); vi.unstubAllGlobals(); });
it('freezes animations and remaining replay delay, then resumes without restarting', () => {
  vi.useFakeTimers();
  let time = 0;
  vi.stubGlobal('performance', { now: () => time });
  const clock = createPreviewTimeline();
  const animation = { pause: vi.fn(), play: vi.fn(), cancel: vi.fn(), playState: 'running' };
  clock.track(animation as unknown as Animation);
  const replay = vi.fn();
  clock.setTimeout(replay, 400);
  time = 100; vi.advanceTimersByTime(100);
  clock.setPaused(true);
  time = 2100; vi.advanceTimersByTime(2000);
  expect(clock.now()).toBe(100);
  expect(replay).not.toHaveBeenCalled();
  expect(animation.pause).toHaveBeenCalledOnce();
  clock.setPaused(false);
  expect(animation.play).toHaveBeenCalledOnce();
  time = 2399; vi.advanceTimersByTime(299);
  expect(replay).not.toHaveBeenCalled();
  time = 2400; vi.advanceTimersByTime(1);
  expect(replay).toHaveBeenCalledOnce();
  clock.dispose();
});
it('resumes gesture frames on the same virtual clock', () => {
  let time = 100;
  let frame: FrameRequestCallback = () => {};
  vi.stubGlobal('performance', { now: () => time });
  vi.stubGlobal('requestAnimationFrame', vi.fn(callback => { frame = callback; return 1; }));
  vi.stubGlobal('cancelAnimationFrame', vi.fn());
  const clock = createPreviewTimeline();
  const render = vi.fn();
  clock.requestAnimationFrame(render);
  clock.setPaused(true);
  time = 1100;
  clock.setPaused(false);
  time = 1116; frame(time);
  expect(render).toHaveBeenCalledWith(116);
  clock.dispose();
});
