export type Principle = { id: string; name: string; statement: string; rationale: string; appliesTo: string[] };
export type Framework = { id: string; name: string; summary: string; useCases: string[]; coreRules: string[] };
export type SlopSignal = { id: string; name: string; description: string; category: string; evidencePattern: string; rationale: string };

export const principles: Principle[] = [
  { id: "traceability", name: "Traceability", statement: "Every element maps to a user, task, or system reason.", rationale: "A stated reason makes decisions reviewable and helps remove decoration without purpose.", appliesTo: ["Product", "Flow", "Screen", "Component", "Code"] },
  { id: "hierarchy-before-decoration", name: "Hierarchy before decoration", statement: "Establish priority and grouping before adding visual treatment.", rationale: "Clear information relationships should carry the interface before decorative effects do.", appliesTo: ["Screen", "Component"] },
  { id: "weakest-sufficient-separator", name: "Use the weakest sufficient separator", statement: "Choose the lightest visual boundary that makes a relationship clear.", rationale: "Unnecessary containers and borders fragment related information.", appliesTo: ["Screen", "Component"] },
  { id: "recognition-over-recall", name: "Recognition over recall", statement: "Make relevant options and context visible when users need them.", rationale: "Visible cues reduce memory burden and support confident choices.", appliesTo: ["Product", "Flow", "Screen", "Content"] },
  { id: "state-matched-feedback", name: "Feedback must match system state", statement: "Communicate outcomes that reflect what the system actually did.", rationale: "Accurate feedback lets users understand progress and choose a safe next action.", appliesTo: ["Flow", "Component", "Code"] },
  { id: "no-dead-ends", name: "No dead ends", statement: "Every screen offers a way forward and a way back.", rationale: "Users must be able to continue or leave a flow safely.", appliesTo: ["Flow", "Screen", "Code"] },
  { id: "truthful-content", name: "Truthful content", statement: "Show only real data, real claims, real states.", rationale: "Unsupported claims and premature success messages undermine trust.", appliesTo: ["Content", "Screen", "Flow"] },

];

export const frameworks: Framework[] = [
  { id: "ideo", name: "IDEO", summary: "Human centered design approach connecting desirability, feasibility, and viability.", useCases: ["Product discovery", "Concept review"], coreRules: ["Ground opportunities in observed human needs", "Explore and test multiple concepts"] },
  { id: "jtbd", name: "JTBD", summary: "A way to understand the progress people seek in a specific situation.", useCases: ["Purpose review", "Context review"], coreRules: ["Describe the situation and desired progress", "Separate user motivation from a proposed feature"] },
  { id: "kano", name: "Kano", summary: "Model for understanding how product attributes affect satisfaction.", useCases: ["Feature prioritization"], coreRules: ["Distinguish basic, performance, and delight attributes", "Validate expectations with users"] },
  { id: "cubi", name: "CUBI", summary: "Compact product experience review lens for clarity, usability, and impact.", useCases: ["Product review"], coreRules: ["Tie critique to user and product context"] },
  { id: "cognitive-walkthrough", name: "Cognitive Walkthrough", summary: "Step-by-step evaluation of whether a new user can discover and perform an action.", useCases: ["Task flow", "Onboarding"], coreRules: ["Check goal formation", "Check action discovery", "Check feedback and progress"] },
  { id: "norman-gulfs", name: "Norman Gulfs", summary: "Evaluate the gap between user intention, available actions, and system feedback.", useCases: ["Task flow", "State review"], coreRules: ["Make possible actions visible", "Make system state interpretable"] },
  { id: "heart-gsm", name: "HEART + GSM", summary: "User experience measures connected to goals, signals, and metrics.", useCases: ["Outcome measurement"], coreRules: ["Connect each metric to a user goal", "Choose observable signals"] },
  { id: "nielsen-heuristics", name: "Nielsen Heuristics", summary: "Usability principles for evaluating interactive systems.", useCases: ["Usability review", "State review"], coreRules: ["Keep system status visible", "Prevent errors", "Support recovery and user control"] },
  { id: "krug", name: "Krug", summary: "Usability guidance focused on making interfaces obvious and easy to scan.", useCases: ["Navigation", "Information architecture"], coreRules: ["Make choices self-evident", "Reduce unnecessary thought"] },
  { id: "5es", name: "5Es", summary: "Experience lens covering entice, enter, engage, exit, and extend.", useCases: ["Journey review"], coreRules: ["Review the experience across its full lifecycle"] },
  { id: "ux-honeycomb", name: "UX Honeycomb", summary: "A set of facets for useful, usable, desirable, findable, accessible, credible, and valuable experiences.", useCases: ["Purpose review", "Product review"], coreRules: ["Evaluate the experience across more than visual appeal"] },
  { id: "cognitive-load", name: "Cognitive Load", summary: "Lens for the mental effort required to understand and act.", useCases: ["Complexity review"], coreRules: ["Remove avoidable memory demands", "Group related information"] },
  { id: "laws-of-ux", name: "Laws of UX", summary: "Collection of principles describing common patterns in human perception and behavior.", useCases: ["Hierarchy", "Cognitive load"], coreRules: ["Apply principles in context and verify with evidence"] },
  { id: "gestalt", name: "Gestalt", summary: "Perceptual principles explaining how people group and interpret visual elements.", useCases: ["Visual hierarchy", "Grouping"], coreRules: ["Use proximity, similarity, continuity, and figure-ground intentionally"] },
  { id: "pour", name: "POUR", summary: "Accessibility principles: perceivable, operable, understandable, and robust.", useCases: ["Accessibility review"], coreRules: ["Check content access", "Check operation", "Check comprehension", "Check compatibility"] },
  { id: "human-dimension", name: "Human Dimension", summary: "Perspective on user capability, context, and human needs in product decisions.", useCases: ["Product discovery"], coreRules: ["Account for varied abilities and circumstances"] },
  { id: "context-dimension", name: "Context Dimension", summary: "Perspective on the environment and circumstances in which the product is used.", useCases: ["Context specificity"], coreRules: ["Make assumptions about context explicit"] },
  { id: "design-system", name: "Design System", summary: "Shared tokens, components, patterns, and rules that keep an interface coherent as it evolves.", useCases: ["Implementation review", "Consistency review"], coreRules: ["Prefer existing components and semantic tokens", "Document deliberate exceptions"] },
];

export const slopSignals: SlopSignal[] = [
  { id: "generic-ui", name: "Generic UI", description: "Common interface patterns appear without product-specific reasoning.", category: "Context", evidencePattern: "Replace the product name and the screen still appears plausible.", rationale: "Generic solutions often miss domain tasks and user needs." },
  { id: "cardification", name: "Cardification", description: "Cards or nested surfaces are used where simple grouping would suffice.", category: "Structure", evidencePattern: "Repeated containers around related content with no distinct action or boundary.", rationale: "Excess surface treatment adds visual noise and separates related information." },
  { id: "fake-dashboard", name: "Fake dashboard", description: "Metrics or charts appear without a clear user decision they support.", category: "Content", evidencePattern: "Decorative KPIs, unexplained numbers, or unsupported trend lines.", rationale: "Invented data can mislead users and create false product credibility." },
  { id: "meaningless-decoration", name: "Meaningless decoration", description: "Visual flourishes do not explain hierarchy, status, or action.", category: "Visual", evidencePattern: "Gradient, glow, illustration, or shape with no semantic role.", rationale: "Decoration competes with functional content without improving understanding." },
  { id: "generic-copy", name: "Generic copy", description: "Vague or promotional wording replaces specific product language.", category: "Content", evidencePattern: "Broad claims, filler copy, or repeated generic labels.", rationale: "Users need accurate language to judge relevance and take action." },
  { id: "excessive-badges", name: "Excessive badges", description: "Many labels use badge styling without a status or categorization need.", category: "Visual", evidencePattern: "Badge clusters with no distinct meaning or decision value.", rationale: "Overuse weakens the meaning of genuine status labels." },
  { id: "excessive-pills", name: "Excessive pill usage", description: "Pill shapes are applied indiscriminately to unrelated controls and content.", category: "Visual", evidencePattern: "Rounded capsule treatment repeated across labels, cards, and buttons.", rationale: "Uniform treatment blurs differences between actions and information." },
  { id: "gradient-glow-overuse", name: "Gradient and glow overuse", description: "High attention effects are used without supporting meaning.", category: "Visual", evidencePattern: "Multiple gradients, glows, or blurred effects behind routine content.", rationale: "Persistent emphasis makes important controls harder to distinguish." },
  { id: "missing-states", name: "Missing states", description: "Interactive components only show their ideal state.", category: "Interaction", evidencePattern: "No loading, empty, error, disabled, or success response where relevant.", rationale: "Users cannot predict outcomes or recover when real conditions vary." },
  { id: "arbitrary-tokens", name: "Arbitrary tokens", description: "Visual values drift from the product's established system.", category: "System", evidencePattern: "One-off color, spacing, radius, or shadow values without a token mapping.", rationale: "Untracked values reduce consistency and make future changes expensive." },
  { id: "component-proliferation", name: "Component proliferation", description: "New components duplicate existing patterns without a distinct need.", category: "System", evidencePattern: "Near-identical controls or surfaces implemented as separate variants.", rationale: "Duplication causes behavior and visual consistency to drift." },
  { id: "equal-prominence", name: "Equal prominence", description: "Primary and secondary content compete at the same visual level.", category: "Hierarchy", evidencePattern: "Several actions or blocks share similar size, contrast, and placement.", rationale: "Users cannot quickly identify the main task or next step." },
];

slopSignals.push(
  { id: "placeholder-leak", name: "Placeholder leak", description: "Placeholder content reaches the reviewed product.", category: "Content", evidencePattern: "Lorem ipsum, John Doe, Acme Inc, $99.99, TODO, stock images.", rationale: "Unmarked placeholders create misleading content." },
  { id: "dead-cta", name: "Dead CTA", description: "A visible action has no working destination.", category: "Flow", evidencePattern: "Button or link has no action, points to #, or leads to a missing screen.", rationale: "Dead actions block task completion." },
  { id: "happy-path-only", name: "Happy path only", description: "Alternate states and paths are missing.", category: "Flow", evidencePattern: "Missing error, empty, no-permission, edit, or delete paths.", rationale: "Real usage requires more than the successful path." },
  { id: "terminology-drift", name: "Terminology drift", description: "One concept has multiple names.", category: "Content", evidencePattern: "At least two names for one concept in the same flow.", rationale: "Inconsistent terms create unnecessary uncertainty." },
  { id: "premature-success", name: "Premature success", description: "Success is shown before confirmation.", category: "State", evidencePattern: "Saved or Done toast appears before the system confirms the operation.", rationale: "Feedback must reflect actual system state." },
  { id: "emoji-decoration", name: "Emoji decoration", description: "Emoji add no useful meaning.", category: "Visual", evidencePattern: "Emoji in headings or labels without a semantic purpose.", rationale: "Decoration should support status, hierarchy, or action." },
);
